version: 0.0
os: linux
files:
  - source: /
    destination: /home/tradis/last_revision
  - source: /deploy/supervisor/
    destination: /etc/supervisor/conf.d/
file_exists_behavior: OVERWRITE
permissions:
  - object: /home/tradis/last_revision
    owner: tradis
    type: 
      - directory
hooks:
  BeforeInstall:
    - location: deploy/scripts/install_libs.sh
      timeout: 600
      runas: root
  AfterInstall:
    - location: deploy/scripts/install_requirements.sh
      timeout: 300
      runas: root
    - location: deploy/scripts/copy_local_config.sh
      timeout: 5
      runas: root
    - location: deploy/scripts/setup_dash.sh
      timeout: 5
      runas: root
  ApplicationStart:
    - location: deploy/scripts/start_server.sh
      timeout: 30
      runas: root
  ApplicationStop:
    - location: deploy/scripts/stop_server.sh
      timeout: 30
      runas: root
