# IBKR account
username: aaa
password: bbb
paper: true

redis:
  host: 127.0.0.1
  port: 6379
  db: 0
  password: null

secret: blablabla=

dashboard_csv_path: dash/dash.csv

instruments:
  - conid: 265598
    symbol: AAPL
    exchange: NASDAQ

  - conid: 461318791
    symbol: MES
    exchange: GLOBEX

  - conid: 461318792
    symbol: MNQ
    exchange: GLOBEX

  - conid: 211651685
    symbol: URA
    exchange: ARCA

  - conid: 508109460
    symbol: MNTS
    exchange: NASDAQ
